steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  secretEnv: ['FIREBASE_ADMIN_SDK']
  args:
       - '-c'
       - |
         echo $$FIREBASE_ADMIN_SDK > ./adminsdk.json &&
         docker build . -t gcr.io/wedding-site-311102/wedding-site
 # Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'wedding-site-service'
  - '--image'
  - 'gcr.io/wedding-site-311102/wedding-site@latest'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
images: ['gcr.io/wedding-site-311102/wedding-site']
availableSecrets:
  secretManager:
  - versionName: projects/wedding-site-311102/secrets/firebase-admin-sdk/versions/1
    env: 'FIREBASE_ADMIN_SDK'